import type { NextPage } from 'next';
import Head from 'next/head';
import { Table } from '../components/Table';
import { useBalance } from '../lib/hooks';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const balanceRes = useBalance();

  return (
    <div className={styles.container}>
      <Head>
        <title>Jackpot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Jackpot!</h1>
        <h2 className={styles.description}>
          Balance: {balanceRes.data?.balance}
        </h2>
        <Table />
      </main>
    </div>
  );
};

export default Home;
